Masciotta02 51
par-tec/esco-playground pull request #53
Opened 2024-07-30 19:30 UTC by masciotta02

Test Matcher Skill

- example labels (VERB + customer satisfaction)
- cloud occupation (search skill into ESCO and create a matcher)

2024-07-30 20:14 UTC, ioggstream requested changes
Good starting point!

Try to structure a test file like the others that we have in the repo.

Work together with your teammates,

2024-07-30 20:14 UTC, ioggstream commented on tests/test_skill_mathcer.py
> +import spacy
Fix file name;)

2024-07-30 20:14 UTC, ioggstream commented on tests/test_skill_mathcer.py
> +nlp = spacy.load("en_core_web_sm")
We use another spacy model in model.py

2024-07-30 20:14 UTC, ioggstream commented on tests/test_skill_mathcer.py
> +# Crea un matcher
Use English

2024-07-30 20:14 UTC, ioggstream commented on tests/test_skill_mathcer.py
> +pattern = [
You can start using only the simplest pattern.

Consider that in the end, patterns must be automatically generated.

2024-07-30 20:14 UTC, ioggstream commented on tests/test_skill_mathcer.py
> +print("*************test_1*************")
Create 3 different test functions, one for each matcher

2024-07-30 20:14 UTC, ioggstream commented on tests/test_skill_mathcer.py
> +pattern3 = [
Where can I find test results?

2024-07-30 20:14 UTC, ioggstream commented on tests/test_skill_mathcer.py
> +    "manage and maintain company IT infrastructure implement hybrid cloud solutions and design cloud architecture and plan migration cloud optimize"
Talk with @Edocampa and try to create a test file together, based on the work that he's doing on the ner yaml file

2024-07-31 07:01 UTC, masciotta02 commented on tests/test_skill_mathcer.py
> +import spacy
i don't understand this suggustesion

2024-07-31 07:04 UTC, masciotta02 commented on tests/test_skill_mathcer.py
> +nlp = spacy.load("en_core_web_sm")
i know, but i don't say how modify the code for implement the model that we use

2024-07-31 07:06 UTC, masciotta02 commented on tests/test_skill_mathcer.py
> +pattern3 = [
run the code .py and print the result

2024-08-04 18:19 UTC, ioggstream commented on tests/test_skill_mathcer.py
> +import spacy
s/mathcer/matcher/ # significa "sostituisci mathcer con matcher" cc: @Edocampa @Manu09011900

2024-08-04 22:29 UTC, ioggstream commented on tests/test_skill_mathcer.py
> -nlp = spacy.load("en_core_web_trf")
I replaced this global variable with a pytest.fixture that is reinitialized before every call.

2024-08-04 22:29 UTC, ioggstream commented on tests/test_skill_mathcer.py
> -"""
don't need this anymore

2024-08-04 22:30 UTC, ioggstream commented on tests/test_skill_mathcer.py
> -]
Replaced with a dict()

2024-08-04 22:30 UTC, ioggstream commented on tests/test_skill_mathcer.py
> -matcher.add("MatcherSkill", [pattern2])  # add pattern
now it's in the test code

2024-08-04 22:30 UTC, ioggstream commented on tests/test_skill_mathcer.py
> -    "I have a long experience in assure customer satisfaction and promise the customer satisfaction "
replaced with an array

2024-08-04 22:31 UTC, ioggstream commented on tests/test_skill_mathcer.py
> -    print(matched_span)
Replaced with test code

2024-08-04 22:31 UTC, ioggstream commented on tests/test_skill_mathcer.py
> -            ]
same as above

2024-08-04 22:32 UTC, ioggstream commented on tests/test_skill_mathcer.py
> +        assert matched_span.text == " ".join(pattern)
for each pattern,
and for each text,
search for matches

2024-08-05 00:22 UTC, ioggstream commented on tests/test_skill_pos_matcher.py
> +    return to_curie(id_), patterns
This is the function generating the patterns for each skill

2024-08-05 00:25 UTC, ioggstream commented on tests/test_skill_pos_matcher.py
> +    yield f  #
This is a feature that generates two generators. You need to write your code replacing the `raise NotImplementedError`.

The `nlp` parameter creates a different test for each nlp fixture

2024-08-05 00:25 UTC, ioggstream commented on tests/test_skill_pos_matcher.py
> +def skills():
returns only the skills related to cloud. This is to speed up the test.

2024-08-05 00:26 UTC, ioggstream commented on tests/test_skill_pos_matcher.py
> +    yield n
Creates 2 models, one vanilla, one with merge_noun_chunks to merge compound words such as "customer satisfaction" or "cloud services". We need to check what happens to lemmas in this case.

2024-08-05 00:27 UTC, ioggstream commented on tests/test_skill_pos_matcher.py
> +    raise NotImplementedError
This is the actual test: you need at first to safe the esco_matcher output in a json file :)

2024-08-22 14:02 UTC, masciotta02 commented
@ioggstream i try to add the code for yaml file test, but not work well... you can give me one suggestion. Thanks

2024-09-05 09:19 UTC, ioggstream commented
Superseeded by #60

2024-09-05 09:19 UTC, closed without merging